#!/usr/bin/env bash
# Configures UFW to block incoming traffic except SSH, HTTP, and HTTPS

apt-get update
apt-get install -y ufw
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw default deny incoming
ufw default allow outgoing
ufw --force enable
