#!/usr/bin/env bash
# Configures Nginx to listen on port 80 on all active IPv4 addresses

sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
service nginx restart
