#!/usr/bin/env bash
# Installs Nginx and configures the default web page

apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.html
service nginx restart
