#!/usr/bin/env bash
# Installs Nginx and configures redirect

sudo apt update -y
sudo apt install nginx -y
sudo sed -i '/server_name _;/a\location /redirect_me {\nreturn 301 https://github.com/23Ihirwe;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
